#!/usr/bin/env python3
"""Generate mesh and texture files needed by the MuJoCo MJCF scene.

The MJCF XMLs (aic_robot.xml, aic_world.xml) reference OBJ/STL mesh files
and PNG textures that were generated by sdformat_mjcf but never committed.
The source assets are GLB files in aic_assets/models/ and UR5e meshes from
the Universal Robots ROS2 Description package.

This script:
1. Parses the XML files to find all referenced mesh/texture files
2. Maps each reference back to its source GLB (or UR5e DAE/STL)
3. Converts and exports the needed files with material-aware merged groups
4. Updates the XML file= attributes to use clean, predictable filenames

Usage:
    python generate_meshes.py
"""

import io
import json
import re
import struct
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path

import numpy as np
import trimesh
from PIL import Image

# Paths
SCRIPT_DIR = Path(__file__).resolve().parent
MJCF_DIR = SCRIPT_DIR.parent / "mjcf"
MESHES_DIR = MJCF_DIR / "meshes"
ASSETS_DIR = SCRIPT_DIR.parents[2] / "aic_assets" / "models"

# UR5e mesh URLs from Universal Robots GitHub
UR5E_GITHUB_BASE = (
    "https://raw.githubusercontent.com/UniversalRobots/"
    "Universal_Robots_ROS2_Description/rolling/meshes/ur5e"
)
UR5E_JOINTS = [
    "base", "shoulder", "upperarm", "forearm", "wrist1", "wrist2", "wrist3",
]

# Map GLB stem -> directory in aic_assets/models/
GLB_LOCATIONS: dict[str, str] = {
    "axia_ft_sensor_visual": "Axia80 M20",
    "basler_cam_visual": "Basler Camera",
    "cam_mount_visual": "Camera Mount",
    "enclosure_visual": "Enclosure",
    "enclosurewalls_visual": "Enclosure",
    "light_visual": "Enclosure",
    "floor_visual": "Floor",
    "walls_visual": "Floor",
    "lc_mount_visual": "LC Mount",
    "lc_plug_visual": "LC Plug",
    "nic_card_mount_visual": "NIC Card Mount",
    "nic_card_visual": "NIC Card",
    "hande_base_visual": "Robotiq Hand-E",
    "hande_finger_visual": "Robotiq Hand-E",
    "sc_mount_visual": "SC Mount",
    "sc_plug_visual": "SC Plug",
    "sc_port_visual": "SC Port",
    "sfp_module_visual": "SFP Module",
    "sfp_mount_visual": "SFP Mount",
    "base_visual": "Task Board Base",
}

# Sorted by length descending so longest prefix matches first
GLB_STEMS_BY_LENGTH = sorted(GLB_LOCATIONS.keys(), key=len, reverse=True)


# ---------------------------------------------------------------------------
# Mesh name parsing
# ---------------------------------------------------------------------------

def parse_mesh_name(mesh_name: str) -> tuple[str, str, str]:
    """Parse a mesh name into (hash, source_key, submesh_name)."""
    match = re.match(r"^([0-9a-f]{64})_(.+)$", mesh_name)
    if not match:
        return "", "", mesh_name
    sha_hash = match.group(1)
    remainder = match.group(2)

    # UR5e STL collision mesh (e.g., "base.stl")
    if remainder.endswith(".stl"):
        joint = remainder[:-4]
        if joint in UR5E_JOINTS:
            return sha_hash, f"ur5e_collision_{joint}", ""

    # GLB stem (longest prefix match)
    for stem in GLB_STEMS_BY_LENGTH:
        if remainder.startswith(stem + "_"):
            return sha_hash, stem, remainder[len(stem) + 1:]
        if remainder == stem:
            return sha_hash, stem, ""

    # UR5e visual mesh
    for joint in UR5E_JOINTS:
        if remainder.startswith(joint + "_eSeries_") or remainder.startswith(
            joint + "_merged_"
        ):
            return sha_hash, f"ur5e_visual_{joint}", remainder[len(joint) + 1:]

    return sha_hash, "", remainder


# ---------------------------------------------------------------------------
# Material color helpers
# ---------------------------------------------------------------------------

def _get_xml_material_rgba(
    mesh_name: str, xml_roots: dict[str, ET.Element],
) -> tuple[float, ...] | None:
    """Look up the RGBA color for a mesh from the XML material definitions."""
    material_name = f"material_{mesh_name}"
    for root in xml_roots.values():
        for mat_elem in root.iter("material"):
            if mat_elem.get("name") == material_name:
                rgba_str = mat_elem.get("rgba", "")
                if rgba_str:
                    return tuple(float(x) for x in rgba_str.split())
    return None


def _get_geom_color(geom: trimesh.Trimesh) -> tuple[float, ...]:
    """Extract the dominant color from a trimesh geometry as (r, g, b, a) in 0-1."""
    vis = geom.visual
    if hasattr(vis, "material"):
        mat = vis.material
        if hasattr(mat, "main_color") and mat.main_color is not None:
            c = np.array(mat.main_color, dtype=float) / 255.0
            return tuple(c)
        if hasattr(mat, "diffuse") and mat.diffuse is not None:
            c = np.array(mat.diffuse, dtype=float)
            if c.max() > 1.0:
                c = c / 255.0
            return tuple(c[:4]) if len(c) >= 4 else tuple(c) + (1.0,)
    # Fallback: average face colors
    if hasattr(vis, "face_colors") and vis.face_colors is not None:
        c = np.mean(vis.face_colors, axis=0) / 255.0
        return tuple(c[:4])
    return (0.5, 0.5, 0.5, 1.0)


def _color_distance(a: tuple[float, ...], b: tuple[float, ...]) -> float:
    """Euclidean distance between two RGBA colors (only RGB channels)."""
    return sum((x - y) ** 2 for x, y in zip(a[:3], b[:3])) ** 0.5


# ---------------------------------------------------------------------------
# Scene geometry helpers
# ---------------------------------------------------------------------------

def _load_scene_geoms(path: Path) -> dict[str, trimesh.Trimesh]:
    """Load a GLB or DAE as a dict of {name: Trimesh} with scene transforms applied.

    GLB files embed scale transforms in the scene graph (e.g., mm→m or cm→m).
    We resolve the full transform path via geometry_nodes and apply it so
    exported vertices are in meters.
    """
    scene = trimesh.load(str(path))
    if isinstance(scene, trimesh.Trimesh):
        return {path.stem: scene}
    if not isinstance(scene, trimesh.Scene):
        return {}

    # geometry_nodes maps geometry_name -> [graph_node_name, ...]
    geom_nodes = getattr(scene.graph, "geometry_nodes", {})

    result: dict[str, trimesh.Trimesh] = {}
    for geom_name, geom in scene.geometry.items():
        transform = np.eye(4)

        # Look up the graph node that references this geometry
        node_names = geom_nodes.get(geom_name, [])
        for node_name in node_names:
            try:
                transform, _ = scene.graph.get(node_name)
                break
            except (ValueError, KeyError):
                continue
        else:
            # Fallback: try direct lookup by geometry name
            try:
                transform, _ = scene.graph.get(geom_name)
            except (ValueError, KeyError):
                pass

        transformed = geom.copy()
        transformed.apply_transform(transform)
        result[geom_name] = transformed

    return result


def _find_named_geom(
    submesh: str, available: dict[str, trimesh.Trimesh],
) -> tuple[str, trimesh.Trimesh] | None:
    """Find a named (non-merged) submesh, handling space/underscore mismatches."""
    if submesh in available:
        return submesh, available[submesh]
    # sdformat_mjcf converts spaces to underscores
    for name, geom in available.items():
        if name.replace(" ", "_") == submesh:
            return name, geom
    return None


def _export_obj(geom: trimesh.Trimesh, path: Path) -> None:
    """Export trimesh as OBJ (vertices should already be in meters)."""
    obj_data = trimesh.exchange.obj.export_obj(geom)
    path.write_text(obj_data)


# ---------------------------------------------------------------------------
# Batch processing: handle named + merged meshes per source file
# ---------------------------------------------------------------------------

def process_scene_meshes(
    source_path: Path,
    mesh_list: list[tuple[str, str]],
    mesh_refs: dict[str, dict],
    xml_roots: dict[str, ET.Element],
    filename_prefix: str,
) -> None:
    """Process all mesh refs for a single source file (GLB or DAE).

    Correctly handles both named submeshes and merged_N groups:
    1. Match named submeshes first (exact or space/underscore match)
    2. Group unclaimed geometries by material color
    3. Assign each merged_N to the best matching color group
    """
    available = _load_scene_geoms(source_path)
    if not available:
        print(f"    WARNING: No geometries in {source_path.name}")
        return

    # Split into named vs merged
    named = [(mn, sub) for mn, sub in mesh_list if not re.match(r"^merged_\d+$", sub)]
    merged = [(mn, sub) for mn, sub in mesh_list if re.match(r"^merged_\d+$", sub)]

    # --- Step 1: match named submeshes ---
    claimed_keys: set[str] = set()
    for mesh_name, submesh in named:
        if not submesh:
            if len(available) == 1:
                key = next(iter(available))
                geom = available[key]
                claimed_keys.add(key)
            else:
                print(f"    WARNING: empty submesh name, {len(available)} geoms")
                continue
        else:
            result = _find_named_geom(submesh, available)
            if result is None:
                print(f"    WARNING: '{submesh}' not found in {source_path.name}")
                continue
            key, geom = result
            claimed_keys.add(key)

        safe = submesh.replace("/", "_").replace("\\", "_") if submesh else source_path.stem
        obj_name = f"{filename_prefix}__{safe}.obj"
        _export_obj(geom, MESHES_DIR / obj_name)
        mesh_refs[mesh_name]["element"].set("file", f"meshes/{obj_name}")
        print(f"    {obj_name} ({len(geom.vertices)} verts)")

    # --- Step 2: handle merged submeshes by material color matching ---
    if not merged:
        return

    unclaimed = {k: v for k, v in available.items() if k not in claimed_keys}
    if not unclaimed:
        print(f"    WARNING: no unclaimed geoms left for {len(merged)} merged refs")
        return

    # Group unclaimed geometries by color
    color_groups: dict[tuple[float, ...], list[trimesh.Trimesh]] = {}
    for gname, geom in unclaimed.items():
        color = _get_geom_color(geom)
        key = tuple(round(c, 2) for c in color[:3])
        color_groups.setdefault(key, []).append(geom)

    # If fewer color groups than merged refs, split the largest group(s)
    while len(color_groups) < len(merged):
        # Find largest group and split it in half
        largest_key = max(color_groups, key=lambda k: len(color_groups[k]))
        geoms = color_groups[largest_key]
        if len(geoms) < 2:
            break  # can't split further
        mid = len(geoms) // 2
        # Use a new synthetic key for the split-off portion
        new_key = largest_key + (len(color_groups),)
        color_groups[new_key] = geoms[mid:]
        color_groups[largest_key] = geoms[:mid]

    # For each merged_N, find best matching color group via XML material color
    used_groups: set[tuple[float, ...]] = set()
    for mesh_name, submesh in merged:
        xml_rgba = _get_xml_material_rgba(mesh_name, xml_roots)
        if xml_rgba is None:
            xml_rgba = (0.5, 0.5, 0.5, 1.0)

        # Find best matching unused color group
        best_key = None
        best_dist = float("inf")
        for ckey in color_groups:
            if ckey in used_groups:
                continue
            dist = _color_distance(xml_rgba, ckey + (1.0,) * (4 - len(ckey)))
            if dist < best_dist:
                best_dist = dist
                best_key = ckey

        if best_key is None:
            # Last resort: use all remaining unclaimed as a single mesh
            remaining = [g for k, gs in color_groups.items()
                         if k not in used_groups for g in gs]
            if remaining:
                combined = trimesh.util.concatenate(remaining) if len(remaining) > 1 else remaining[0]
                obj_name = f"{filename_prefix}__{submesh}.obj"
                _export_obj(combined, MESHES_DIR / obj_name)
                mesh_refs[mesh_name]["element"].set("file", f"meshes/{obj_name}")
                print(f"    {obj_name} ({len(combined.vertices)} verts, fallback)")
            continue

        used_groups.add(best_key)
        geoms = color_groups[best_key]
        combined = trimesh.util.concatenate(geoms) if len(geoms) > 1 else geoms[0]

        obj_name = f"{filename_prefix}__{submesh}.obj"
        _export_obj(combined, MESHES_DIR / obj_name)
        mesh_refs[mesh_name]["element"].set("file", f"meshes/{obj_name}")
        print(f"    {obj_name} ({len(combined.vertices)} verts, {len(geoms)} geoms merged)")


# ---------------------------------------------------------------------------
# Texture extraction
# ---------------------------------------------------------------------------

def extract_glb_textures(glb_path: Path) -> dict[str, Image.Image]:
    """Extract texture images from a GLB file."""
    with open(glb_path, "rb") as f:
        data = f.read()

    _magic, _version, length = struct.unpack("<III", data[:12])
    offset = 12
    json_data = None
    bin_data = None
    while offset < length:
        chunk_len, chunk_type = struct.unpack("<II", data[offset : offset + 8])
        chunk_data = data[offset + 8 : offset + 8 + chunk_len]
        type_str = chunk_type.to_bytes(4, "little").decode("ascii", errors="replace")
        if type_str == "JSON":
            json_data = json.loads(chunk_data)
        elif type_str.startswith("BIN"):
            bin_data = chunk_data
        offset += 8 + chunk_len

    textures: dict[str, Image.Image] = {}
    if not json_data or not bin_data:
        return textures

    for img_info in json_data.get("images", []):
        bv = json_data["bufferViews"][img_info["bufferView"]]
        bo = bv.get("byteOffset", 0)
        img_bytes = bin_data[bo : bo + bv["byteLength"]]
        img = Image.open(io.BytesIO(img_bytes))
        textures[img_info.get("name", f"texture_{bv.get('byteOffset', 0)}")] = img

    return textures


# ---------------------------------------------------------------------------
# UR5e mesh download
# ---------------------------------------------------------------------------

def download_ur5e_mesh(joint: str, mesh_type: str, output_path: Path) -> bool:
    if mesh_type == "collision":
        url = f"{UR5E_GITHUB_BASE}/collision/{joint}.stl"
    else:
        url = f"{UR5E_GITHUB_BASE}/visual/{joint}.dae"
    try:
        print(f"  Downloading {url}")
        urllib.request.urlretrieve(url, str(output_path))
        return True
    except Exception as e:
        print(f"  ERROR downloading {url}: {e}")
        return False


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def process_xml_files() -> None:
    MESHES_DIR.mkdir(parents=True, exist_ok=True)

    xml_files = {
        "robot": MJCF_DIR / "aic_robot.xml",
        "world": MJCF_DIR / "aic_world.xml",
    }

    # Parse XML files
    xml_trees: dict[str, ET.ElementTree] = {}
    xml_roots: dict[str, ET.Element] = {}
    for xml_key, xml_path in xml_files.items():
        tree = ET.parse(xml_path)
        xml_trees[xml_key] = tree
        xml_roots[xml_key] = tree.getroot()

    # Collect mesh and texture references
    mesh_refs: dict[str, dict] = {}
    texture_refs: dict[str, dict] = {}

    for xml_key, root in xml_roots.items():
        for mesh_elem in root.iter("mesh"):
            name = mesh_elem.get("name", "")
            mesh_refs[name] = {
                "file": mesh_elem.get("file", ""),
                "content_type": mesh_elem.get("content_type", ""),
                "xml_key": xml_key,
                "element": mesh_elem,
            }
        for tex_elem in root.iter("texture"):
            name = tex_elem.get("name", "")
            file_attr = tex_elem.get("file", "")
            if file_attr and (file_attr.endswith(".png") or "meshes/" in file_attr):
                texture_refs[name] = {
                    "file": file_attr,
                    "xml_key": xml_key,
                    "element": tex_elem,
                }

    print(f"Found {len(mesh_refs)} mesh refs, {len(texture_refs)} texture refs")

    # Group meshes by source
    glb_meshes: dict[str, list[tuple[str, str]]] = {}
    ur5e_collision: list[tuple[str, str]] = []
    ur5e_visual: dict[str, list[tuple[str, str]]] = {}

    for mesh_name in mesh_refs:
        _hash, source, submesh = parse_mesh_name(mesh_name)
        if source.startswith("ur5e_collision_"):
            ur5e_collision.append((mesh_name, source.removeprefix("ur5e_collision_")))
        elif source.startswith("ur5e_visual_"):
            joint = source.removeprefix("ur5e_visual_")
            ur5e_visual.setdefault(joint, []).append((mesh_name, submesh))
        elif source in GLB_LOCATIONS:
            glb_meshes.setdefault(source, []).append((mesh_name, submesh))
        else:
            print(f"  WARNING: unmatched mesh: {mesh_name}")

    # --- GLB meshes ---
    print(f"\n=== Converting {len(glb_meshes)} GLB files ===")
    for glb_stem, mesh_list in sorted(glb_meshes.items()):
        glb_path = ASSETS_DIR / GLB_LOCATIONS[glb_stem] / f"{glb_stem}.glb"
        if not glb_path.exists():
            print(f"  SKIP: {glb_path} not found")
            continue
        print(f"\n  {glb_stem}.glb ({len(mesh_list)} meshes)")
        process_scene_meshes(glb_path, mesh_list, mesh_refs, xml_roots, glb_stem)

    # --- UR5e collision (STL) ---
    print(f"\n=== UR5e collision ({len(ur5e_collision)} STLs) ===")
    for mesh_name, joint in ur5e_collision:
        stl_path = MESHES_DIR / f"ur5e_{joint}.stl"
        if not stl_path.exists():
            download_ur5e_mesh(joint, "collision", stl_path)
        mesh_refs[mesh_name]["element"].set("file", f"meshes/ur5e_{joint}.stl")
        print(f"  ur5e_{joint}.stl")

    # --- UR5e visual (DAE -> OBJ) ---
    print(f"\n=== UR5e visual ({len(ur5e_visual)} joints) ===")
    for joint, mesh_list in sorted(ur5e_visual.items()):
        dae_path = MESHES_DIR / f"ur5e_{joint}.dae"
        if not dae_path.exists():
            if not download_ur5e_mesh(joint, "visual", dae_path):
                continue
        print(f"\n  ur5e_{joint}.dae ({len(mesh_list)} meshes)")
        process_scene_meshes(dae_path, mesh_list, mesh_refs, xml_roots, f"ur5e_{joint}")

    # --- Textures ---
    print(f"\n=== Extracting {len(texture_refs)} textures ===")
    for tex_name, tex_info in texture_refs.items():
        match = re.match(r"^texture_([0-9a-f]{64})_(.+)$", tex_name)
        if not match:
            continue
        remainder = match.group(2)

        glb_stem = None
        submesh_part = None
        for stem in GLB_STEMS_BY_LENGTH:
            if remainder.startswith(stem + "_"):
                glb_stem = stem
                submesh_part = remainder[len(stem) + 1:]
                break
        if glb_stem is None:
            continue

        glb_path = ASSETS_DIR / GLB_LOCATIONS[glb_stem] / f"{glb_stem}.glb"
        if not glb_path.exists():
            continue

        textures = extract_glb_textures(glb_path)
        if not textures:
            continue

        safe_name = f"{glb_stem}__{submesh_part}.png"
        png_path = MESHES_DIR / safe_name

        if len(textures) == 1:
            img = next(iter(textures.values()))
        else:
            img = next(
                (v for k, v in textures.items() if submesh_part and k in submesh_part),
                next(iter(textures.values())),
            )
        img.save(str(png_path))
        tex_info["element"].set("file", f"meshes/{safe_name}")
        print(f"  {safe_name} ({img.size[0]}x{img.size[1]})")

    # --- Write XML ---
    print("\n=== Updating XML ===")
    for xml_key, xml_path in xml_files.items():
        xml_trees[xml_key].write(str(xml_path), xml_declaration=False, encoding="unicode")
        print(f"  {xml_path.name}")

    total = len(list(MESHES_DIR.iterdir()))
    print(f"\nDone! {total} files in {MESHES_DIR}")


if __name__ == "__main__":
    process_xml_files()
